Javaトランプカードプロジェクト: jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack Class Reference
jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack Class Reference
ブラックジャッククラス
Public Member Functions
BlackJack ()
コンストラクタ
TrumpCards getTrumpCards ()
ゲッター
void setTrumpCards (TrumpCards trumpCards)
セッター
Player getPlayer ()
ゲッター
void setPlayer (Player player)
セッター
Player getDealer ()
ゲッター
void setDealer (Player dealer)
セッター
boolean getGameEndFlag ()
ゲッター
void setGameEndFlag (boolean gameEndFlag)
セッター
void gameInit ()
ゲーム初期化
void playerHit ()
プレイヤーヒット
void playerStand ()
プレイヤースタンド
int getScore (ArrayList< Card > cards, int cardsCnt)
手札から現在のスコア取得
int gameJudgment ()
ゲーム勝敗判定
Static Public Attributes
static final int DEF_SHUFFLE_CNT = 10
Private Member Functions
void dealerHit ()
ディーラーヒット
void dealerStand ()
ディーラースタンド
Private Attributes
TrumpCards trumpCards
トランプカード
Player player
プレイヤー
Player dealer
ディーラー
boolean gameEndFlag
ゲーム終了フラグ
Detailed Description
ブラックジャッククラス
Definition at line 26 of file BlackJack.java.
Constructor & Destructor Documentation
BlackJack()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.BlackJack ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 41 of file BlackJack.java.
Member Function Documentation
dealerHit()
private void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit () private
ディーラーヒット
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 214 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerStand().
dealerStand()
private void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerStand () private
ディーラースタンド
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 239 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit().
gameInit()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit ()
ゲーム初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 156 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.BlackJack(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.main().
gameJudgment()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameJudgment ()
ゲーム勝敗判定
Returns
ゲーム勝敗判定
1 : プレイヤーの勝利
0 : 引き分け
-1 : プレイヤーの敗北
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 311 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getDealer()
public Player jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.getDealer ()
ゲッター
Returns
ディーラー
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 106 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getGameEndFlag()
public boolean jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.getGameEndFlag ()
ゲッター
Returns
ディーラー
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 131 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getPlayer()
public Player jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.getPlayer ()
ゲッター
Returns
プレイヤー
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 81 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getScore()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.getScore (ArrayList< Card > cards, int cardsCnt)
手札から現在のスコア取得
Parameters
[in] ArrayList<Card> cards 手札
[in] int cardsCnt 手札枚数
Returns
現在のスコア
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 253 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameJudgment(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getTrumpCards()
TrumpCards jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.getTrumpCards ()
ゲッター
Returns
トランプカード
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 56 of file BlackJack.java.
playerHit()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit ()
プレイヤーヒット
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 184 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.main().
playerStand()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerStand ()
プレイヤースタンド
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 202 of file BlackJack.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.main(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit().
setDealer()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.setDealer (Player dealer)
セッター
Parameters
[in] Player dealer ディーラー
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 119 of file BlackJack.java.
setGameEndFlag()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.setGameEndFlag (boolean gameEndFlag)
セッター
Parameters
[in] boolean gameEndFlag ゲーム終了フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 144 of file BlackJack.java.
setPlayer()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.setPlayer (Player player)
セッター
Parameters
[in] Player player プレイヤー
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 94 of file BlackJack.java.
setTrumpCards()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.setTrumpCards (TrumpCards trumpCards)
セッター
Parameters
[in] TrumpCards trumpCards トランプカード
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 69 of file BlackJack.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/java_trumpcards/BlackJack.java