Javaトランプカードプロジェクト: jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player Class Reference
jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player Class Reference
プレイヤークラス
Public Member Functions
Player ()
コンストラクタ
ArrayList< Card > getCards ()
ゲッター
void setCards (ArrayList< Card > cards)
セッター
int getCardsCnt ()
ゲッター
void setCardsCnt (int cardsCnt)
セッター
int getScore ()
ゲッター
void setScore (int score)
セッター
Private Attributes
ArrayList< Card > cards
プレイヤーカード
int cardsCnt
プレイヤーカード枚数
int score
プレイヤースコア
Detailed Description
プレイヤークラス
Definition at line 26 of file Player.java.
Constructor & Destructor Documentation
Player()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.Player ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 39 of file Player.java.
Member Function Documentation
getCards()
ArrayList< Card > jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.getCards ()
ゲッター
Returns
プレイヤーカード
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 53 of file Player.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameJudgment(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getCardsCnt()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.getCardsCnt ()
ゲッター
Returns
プレイヤーカード枚数
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 78 of file Player.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameJudgment(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJackMain.showStatus().
getScore()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.getScore ()
ゲッター
Returns
プレイヤースコア
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 103 of file Player.java.
setCards()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.setCards (ArrayList< Card > cards)
セッター
Parameters
[in] ArrayList<Card> cards プレイヤーカード
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 66 of file Player.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit().
setCardsCnt()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.setCardsCnt (int cardsCnt)
セッター
Parameters
[in] int cardsCnt プレイヤーカード枚数
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 91 of file Player.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit().
setScore()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Player.setScore (int score)
セッター
Parameters
[in] int score プレイヤースコア
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 116 of file Player.java.
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/java_trumpcards/Player.java