Javaトランプカードプロジェクト: jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards Class Reference
jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards Class Reference
トランプカードクラス
Public Member Functions
TrumpCards (int jokerCnt)
コンストラクタ
ArrayList< Card > getDeck ()
ゲッター
void setDeck (ArrayList< Card > deck)
セッター
int getDeckDrowCnt ()
ゲッター
void setDeckDrowCnt (int deckDrowCnt)
セッター
int getDeckCnt ()
ゲッター
void setDeckCnt (int deckCnt)
セッター
void shuffle ()
山札シャッフル
Card drowCard ()
山札配る
Static Public Attributes
static final int DEF_CARD_CNT = (13 * 4)
Private Member Functions
void cardsInit ()
カード初期化
void deckInit ()
山札初期化
void deckDrowFlagInit ()
山札ドローフラグ初期化
Private Attributes
ArrayList< Card > deck
山札
int deckDrowCnt
山札配った枚数
int deckCnt
山札枚数
Detailed Description
トランプカードクラス
Definition at line 27 of file TrumpCards.java.
Constructor & Destructor Documentation
TrumpCards()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.TrumpCards (int jokerCnt)
コンストラクタ
Parameters
[in] int jokerCnt ジョーカー枚数
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 42 of file TrumpCards.java.
Member Function Documentation
cardsInit()
private void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.cardsInit () private
カード初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 131 of file TrumpCards.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.TrumpCards().
deckDrowFlagInit()
private jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.deckDrowFlagInit () private
山札ドローフラグ初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 182 of file TrumpCards.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.deckInit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.shuffle().
deckInit()
private void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.deckInit () private
山札初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 169 of file TrumpCards.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.TrumpCards().
drowCard()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.drowCard ()
山札配る
Returns
カードクラス
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 210 of file TrumpCards.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.dealerHit(), jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.playerHit().
getDeck()
public ArrayList< Card > jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.getDeck ()
ゲッター
Returns
山札
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 56 of file TrumpCards.java.
getDeckCnt()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.getDeckCnt ()
ゲッター
Returns
山札枚数
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 106 of file TrumpCards.java.
getDeckDrowCnt()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.getDeckDrowCnt ()
ゲッター
Returns
山札配った枚数
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 81 of file TrumpCards.java.
setDeck()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.setDeck (ArrayList< Card > deck)
セッター
Parameters
[in] ArrayList<Card> deck 山札
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 69 of file TrumpCards.java.
setDeckCnt()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.setDeckCnt (int deckCnt)
セッター
Parameters
[in] int deckCnt 山札枚数
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 119 of file TrumpCards.java.
setDeckDrowCnt()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.setDeckDrowCnt (int deckDrowCnt)
セッター
Parameters
[in] int deckDrowCnt 山札配った枚数
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 94 of file TrumpCards.java.
shuffle()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.shuffle ()
山札シャッフル
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 196 of file TrumpCards.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.BlackJack.gameInit().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/java_trumpcards/TrumpCards.java