Javaトランプカードプロジェクト: jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card Class Reference
jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card Class Reference
カードクラス
Public Member Functions
Card ()
コンストラクタ
int getType ()
ゲッター
void setType (int type)
セッター
int getValue ()
ゲッター
void setValue (int value)
セッター
boolean getDrowFlag ()
ゲッター
void setDrowFlag (boolean drowFlag)
セッター
String getExt ()
ゲッター
void setExt (String ext)
セッター
Static Public Attributes
static final int DEF_CARD_TYPE_JOKER = 0
static final int DEF_CARD_TYPE_SPADE = 1
static final int DEF_CARD_TYPE_CLOVER = 2
static final int DEF_CARD_TYPE_HEART = 3
static final int DEF_CARD_TYPE_DIAMOND = 4
static final int DEF_CARD_TYPE_MIN = DEF_CARD_TYPE_JOKER
static final int DEF_CARD_TYPE_MAX = DEF_CARD_TYPE_DIAMOND
static final int DEF_CARD_VALUE_JOKER = 0
static final int DEF_CARD_VALUE_MIN = 0
static final int DEF_CARD_VALUE_MAX = 13
Private Attributes
int type
カード種類
int value
カード値
boolean drowFlag
カード払い出しフラグ
String ext
カード拡張情報など(カード別にメッセージを出す場合など)
Detailed Description
カードクラス
Definition at line 25 of file Card.java.
Constructor & Destructor Documentation
Card()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.Card ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 51 of file Card.java.
Member Function Documentation
getDrowFlag()
public boolean jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.getDrowFlag ()
ゲッター
Returns
カード払い出しフラグ
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 120 of file Card.java.
getExt()
public String jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.getExt ()
ゲッター
Returns
カード払い出しフラグ
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 145 of file Card.java.
getType()
public int jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.getType ()
ゲッター
Returns
カード種類
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 66 of file Card.java.
getValue()
public jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.getValue ()
ゲッター
Returns
カード値
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 93 of file Card.java.
setDrowFlag()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.setDrowFlag (boolean drowFlag)
セッター
Parameters
[in] boolean drowFlag カード払い出しフラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 133 of file Card.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.cardsInit(), and jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.drowCard().
setExt()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.setExt (String ext)
セッター
Parameters
[in] String ext カード拡張情報など(カード別にメッセージを出す場合など)
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 158 of file Card.java.
setType()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.setType (int type)
セッター
Parameters
[in] int type カード種類
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 79 of file Card.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.cardsInit().
setValue()
public void jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.Card.setValue (int value)
セッター
Parameters
[in] int value カード値
Returns
ありません
Author
Yuta Yoshinaga
Date
2019.04.27
Definition at line 106 of file Card.java.
Referenced by jp.gr.java_conf.yuta_yoshinaga.java_trumpcards.TrumpCards.cardsInit().
The documentation for this class was generated from the following file:
jp/gr/java_conf/yuta_yoshinaga/java_trumpcards/Card.java